safe: true
lsi: false
highlighter: pygments
markdown: redcarpet3
encoding: utf-8
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "lax_spacing", "space_after_headers", "superscript"]
  
# baseurl: /my-site-name
# permalink: /docs/:title.html